services:
  db:
    image: postgis/postgis:17-3.5
    container_name: itinerarium_db
    restart: unless-stopped

    environment:
      - POSTGRES_DB=itinerarium
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    
    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
