import type { Metadata } from "next";
import { Inter, Instrument_Serif, Montserrat } from "next/font/google";
import "./globals.css";

const instrumentSerif = Instrument_Serif({
  weight: ['400'],
  variable: "--font-instrument-serif",
  style: ['normal', 'italic']
})

const inter = Inter({
  weight: ['400', '600', '700'],
  variable: "--font-inter",
  style: ['normal']
})

const montserrat = Montserrat({
  weight: ['400', '600', '700'],
  variable: "--font-montserrat",
  style: ["normal"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className={`${inter.variable} ${instrumentSerif.variable} ${montserrat.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
